In [20]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

num1 = int(input("Enter 1st number: "))
num2 = int(input("Enter 2nd number: "))
num3 = int(input("Enter 3rd number: "))

inp_arr = np.array([num1,num2,num3])

inp_arr

Enter 1st number: 20
Enter 2nd number: 80
Enter 3rd number: 10


array([20, 80, 10])

In [26]:
indices = [np.where(num == arr)[0] for num in inp_arr]
indices = [ind[0] for ind in indices]
indices

[1, 7, 0]

Question 2:

In [30]:
# Create a boolean mask for elements greater than 20
arr = np.array([5, 12, 17, 24, 29, 33, 41, 56])

mask = arr>20
arr[mask]

array([24, 29, 33, 41, 56])

In [31]:
# Use the mask to filter the array. Set arr>20 to -1
arr[mask] = -1
arr

array([ 5, 12, 17, -1, -1, -1, -1, -1])

In [34]:
# Create a new mask for even elements
# Use the mask to filter the array
mask = arr%2 == 0
arr[mask]

array([12])

Question 3:

In [39]:
arr1 = np.array([['hello', 'good'], ['morning', 'night']])
arr2 = np.array([['world', 'morning'], ['everyone', 'moon']])


In [42]:
np.char.add(arr1,arr2)

array([['helloworld', 'goodmorning'],
       ['morningeveryone', 'nightmoon']], dtype='<U15')

In [43]:
np.char.add(np.char.capitalize(arr1),arr2)

array([['Helloworld', 'Goodmorning'],
       ['Morningeveryone', 'Nightmoon']], dtype='<U15')

In [52]:
np.char.multiply(np.char.add((np.char.capitalize(arr1)),(arr2)),2)[0]

array(['HelloworldHelloworld', 'GoodmorningGoodmorning'], dtype='<U30')